(import (scheme base)
        (scheme file)
        (scheme write)
        (ports day1) (ports day2) (ports day3) (ports day4)
        (prefix (ports day5) day5-) (prefix (ports day6) day6-)
        (srfi srfi-64))
(let ((test-name "guile-test"))
           (include "runner.scm")
           (include "test-common.scm"))
