(import (scheme base)
        (srfi 64)
        (aoc data)
        (scheme write))
(include "test/runner.scm")
(display "test, \t status \n")
(test-begin "data tests")
(test-equal "negative sign" -1 (sign -7))
(test-equal "zero sign" 0 (sign 0))
(test-equal "positive sign" 1 (sign 100))
(test-equal "range inclusive" '(7 8 9 10 11 12) (range-inclusive 7 12))
(test-end "data tests")
